# http://idratherbewriting.com/learnapidoc/pubapis_openapi_step4_paths_object.html
openapi: "3.0.0"

info:
  title: StoryPlow
  description: "Working API for StoryPlow Submission Management System."
  version: "1.0"
  termsOfService:
  contact:
    name: davidlday
    url: http://www.prosegrinder.com
    email: dday376@gmail.com
  license:
    name: GPL-3.0
    url:

servers:
  - url: https://storyplow.prosegrinder.com/api
    description: Production server

paths:
  /publishers:
    get:
      tags:
      summary:
      description:
      operationId:
      externalDocs:
      parameters:
      responses:
      # deprecated:
      # security:
      # servers:
      # requestBody:
      # callbacks:

  /markets:
    get:
      tags:
      summary:
      description:
      operationId:
      externalDocs:
      parameters:
      responses:
      # deprecated:
      # security:
      # servers:
      # requestBody:
      # callbacks:

  /calls:
    get:
      tags:
      summary:
      description:
      operationId:
      externalDocs:
      parameters:
      responses:
      # deprecated:
      # security:
      # servers:
      # requestBody:
      # callbacks:

  /submissions:
    get:
      tags:
      summary:
      description:
      operationId:
      externalDocs:
      parameters:
      responses:
      # deprecated:
      # security:
      # servers:
      # requestBody:
      # callbacks:


components:

security:

tags:

externalDocs:
